---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener
  labels:
    app: url-shortener
    service: url-shortener-srv
spec:
  selector:
    matchLabels:
      app: url-shortener
      service: url-shortener-srv
  template:
    metadata:
      labels:
        app: url-shortener
        service: url-shortener-srv
    spec:
      containers:
        - name: url-shortener
          image: francescoforestiphoopsit/url_shortener_arm32v7:0.0.2
          imagePullPolicy: Always
  replicas: 1
  strategy:
    type: Recreate
---
apiVersion: v1
kind: Service
metadata:
  name: url-shortener
  labels:
    app: url-shortener
    service: url-shortener-srv
spec:
  selector:
    app: url-shortener
    service: url-shortener-srv
  type: LoadBalancer
  ports:
    - port: 8080
      name: proxy-port
      targetPort: 8080
---
#apiVersion: extensions/v1beta1
#kind: Ingress
#metadata:
#  name: url-shortener
#spec:
#  rules:
#    - host: "pi401"
#      http:
#        paths:
#          - path: /url_shortener
#            backend:
#              serviceName: url-shortener-srv
#              servicePort: 8080
